[server]
# 服务启动端口
# Port for the server to start on
port = 8080

# 请求access日志路径，相对目录，相对于启动目录；也可以是绝对路径
# Path for access log, relative to the startup directory or an absolute path
access_log_path = "logs/access.log"

# 请求error日志路径，相对目录，相对于启动目录；也可以是绝对路径
# Path for error log, relative to the startup directory or an absolute path
error_log_path = "logs/error.log"

# 业务日志路径，相对目录，相对于启动目录；也可以是绝对路径
# Path for application log, relative to the startup directory or an absolute path
broker_log_path = "logs/broker.log"

[jwt]
# 多个broker节点，必须保持一致;
# In a multi-broker environment, the configuration must be consistent

# 生成token的密钥
# Secret key for generating JWT tokens
secret = "please_modify"

# token默认过期时间，单位秒
# Default token expiration time, in seconds
expire = 30

[redis]
# 多个broker节点，必须保持一致;
# In a multi-broker environment, the configuration must be consistent

# redis地址, 单地址为单例模式， 多地址为集群模式；单例模式下，db必须设置; 
# Redis addresses, a single address for standalone mode, multiple addresses for cluster mode; in standalone mode, 'db' must be set; 
addrs = ["please_modify_1:6379", "please_modify_2:6379"]

# redis密码; 
# Redis password; 
password = "please_modify"

# redis数据库;
# Redis database (used in standalone mode); 
db = 0

# redis连接池大小，0表示默认值 cpu核数*10
# Size of the Redis connection pool, 0 indicates the default value (10 * number of CPU cores)
pool_size = 0

[sse]
# 多个broker节点，必须保持一致;
# In a multi-broker environment, the configuration must be consistent

# 每个sse连接，服务端发送心跳的间隔时间
# Heartbeat interval for each SSE connection, in seconds
heartbeat_interval = 30

# 每个设备，缓存的最大消息帧数
# Maximum number of message frames cached per device
device_frame_cache_size = 10

# 每个设备，缓存的消息帧过期时间
# Expiration time for cached message frames per device, in seconds
device_frame_cache_expire = 604800
