[server]
# 服务启动端口
port = 8080
# 静态文件目录，相对目录，相对于启动目录；也可以是绝对路径
static_dir = "static"
# 请求access日志路径，相对目录，相对于启动目录；也可以是绝对路径
access_log_path = "logs/access.log"
# 请求error日志路径，相对目录，相对于启动目录；也可以是绝对路径
error_log_path = "logs/error.log"
# 业务日志路径，相对目录，相对于启动目录；也可以是绝对路径
app_log_path = "logs/app.log"

[jwt]
# 生成token的密钥
secret = "abc123"
# token默认过期时间，单位秒
expire = 3600

[redis]
# redis地址, 单地址为单例模式， 多地址为集群模式；单例模式下，db必须设置
addrs = ["114.116.222.136:6379"]
# redis密码
password = "Yfw68Test2019"
# redis数据库
db = 5
# redis连接池大小
pool_size = 10

[sse]
# 每个sse连接，服务端发送心跳的间隔时间
heartbeat_interval = 30
# 每个设备，缓存的最大消息帧数
device_frame_cache_size = 10
# 每个设备，缓存的消息帧过期时间
device_frame_cache_expire = 604800