[server]
# 监听地址，多个地址用逗号分隔，默认监听所有地址
# Listening addresses, multiple addresses separated by commas, default listens on all addresses
ipv4 = "0.0.0.0"

# 监听的IPV6地址，多个地址用逗号分隔，例如："fe80::abcd:1234,2001:db8::1" 默认不监听
# Listening IPv6 addresses, multiple addresses separated by commas, e.g.: "fe80::abcd:1234,2001:db8::1" Default does not listen
ipv6 = ""

# 服务启动端口
# Port for the server to start on
port = 8080


[access_log]
# 请求access日志路径，相对目录，相对于启动目录；也可以是绝对路径
# Path for access log, relative to the startup directory or an absolute path
path = "logs/access.log"

# 单个日志文件的最大大小，单位MB
# Maximum size of a single log file, in MB
max_mega_bytes = 100

# 保留的旧日志文件个数
# Number of old log files to retain
max_backups = 7

# 日志文件保留天数
# Number of days to retain log files
max_age_days = 30

# 是否压缩旧的日志文件
# Whether to compress old log files
compress = true

[error_log]
# 请求error日志路径，相对目录，相对于启动目录；也可以是绝对路径
# Path for error log, relative to the startup directory or an absolute path
path = "logs/error.log"

# 单个日志文件的最大大小，单位MB
# Maximum size of a single log file, in MB
max_mega_bytes = 100

# 保留的旧日志文件个数
# Number of old log files to retain
max_backups = 7

# 日志文件保留天数
# Number of days to retain log files
max_age_days = 30

# 是否压缩旧的日志文件
# Whether to compress old log files
compress = true

[broker_log]
# 业务日志路径，相对目录，相对于启动目录；也可以是绝对路径
# Path for application log, relative to the startup directory or an absolute path
path = "logs/broker.log"

# 业务日志级别， 可选值： debug, info, warn, error
# Log level for the broker, options: debug, info, warn, error
level = "info"

# 单个日志文件的最大大小，单位MB
# Maximum size of a single log file, in MB
max_mega_bytes = 100

# 保留的旧日志文件个数
# Number of old log files to retain
max_backups = 7

# 日志文件保留天数
# Number of days to retain log files
max_age_days = 30

# 是否压缩旧的日志文件
# Whether to compress old log files
compress = true

[jwt]
# 多个broker节点，必须保持一致;
# In a multi-broker environment, the configuration must be consistent

# 生成token的密钥
# Secret key for generating JWT tokens
secret = "iech7Ahquighu4ouma"

# token默认过期时间，单位秒
# Default token expiration time, in seconds
expire = 3600

[redis]
# 多个broker节点，必须保持一致;
# In a multi-broker environment, the configuration must be consistent

# redis地址, 单地址为单例模式， 多地址为集群模式；单例模式下，db必须设置; 
# Redis addresses, a single address for standalone mode, multiple addresses for cluster mode; in standalone mode, 'db' must be set; 
addrs = ["192.168.2.252:6379"]

# redis密码; 
# Redis password; 
password = "yaofangwang2018"

# redis数据库;
# Redis database (used in standalone mode); 
db = 5

# redis连接池大小，0表示默认值 cpu核数*10
# Size of the Redis connection pool, 0 indicates the default value (10 * number of CPU cores)
pool_size = 0

[sse]
# 多个broker节点，必须保持一致;
# In a multi-broker environment, the configuration must be consistent

# 每个sse连接，服务端发送心跳的间隔时间
# Heartbeat interval for each SSE connection, in seconds
heartbeat_interval = 30

# 每个设备，缓存的最大消息帧数
# Maximum number of message frames cached per device
device_frame_cache_size = 10

# 每个设备，缓存的消息帧过期时间
# Expiration time for cached message frames per device, in seconds
device_frame_cache_expire = 604800

[callback]
# 多个broker节点，必须保持一致;
# In a multi-broker environment, the configuration must be consistent
# 默认向指定的redis频道发送消息，可以自定义回调地址，系统向该地址Post一个json数据
# By default, messages are sent to the specified Redis channel. 
# You can customize the callback address, and the system will post a JSON data to that address
# user_online = "http://127.0.0.1:8080/callback/user_online"
# user_offline = "http://127.0.0.1:8080/callback/user_offline"
# device_online = "http://127.0.0.1:8080/callback/device_online"
# device_offline = "http://127.0.1.1:8080/callback/device_offline"